#!/bin/sh
set -e

lb config noauto \
  --mode debian \
  --distribution bookworm \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian" \
  --mirror-chroot "http://deb.debian.org/debian" \
  --mirror-binary "http://deb.debian.org/debian" \
  --security true \
  --bootappend-live "boot=live components username=energykit hostname=energykit-installer" \
  --iso-application "EnergyKit Appliance Installer" \
  --iso-publisher "EnergyKit" \
  --iso-volume "ENERGYKIT"
